import { hidePassword, showPassword, category, fullName, atSign, location, search, voiceSearch, decrease, increase, wishlist, home, pageList, order, language, profile, notification, currencyConverter, settings, headerArrow, markRead, discount, offer, passChange, topUp, editProfileImage, call, calender, password, BottomHome, BottomSearch, BottomCategory, BottomCart, facebook, linkedIn, twitter, orderId, chat, sideArrow, unSelected, Selected, cart, selectedTab, Mywishlist, Delete, dropDown, truck, map, mapPin, currentLocation, work, OrderDetails, into, select, share, star, LightStar, deliveryTruck, payment, refund, drawerArrow, dark, rtl, darkIcon, signOut, hindi,arabic,korea,australianDollar,dollar,euro,rupees,koreanWon ,CashOnDelievry} from "../assets/icons";


export const Icons = {
    hidePassword: hidePassword,
    showPassword: showPassword,
    fullName: fullName,
    category: category,
    atSign: atSign,
    location: location,
    search: search,
    voiceSearch: voiceSearch,
    decrease: decrease,
    increase: increase,
    wishlist: wishlist,
    home: home,
    pageList: pageList,
    order: order,
    language: language,
    profile: profile,
    notification: notification,
    currencyConverter: currencyConverter,
    settings: settings,
    headerArrow: headerArrow,
    markRead: markRead,
    discount: discount,
    offer: offer,
    passChange: passChange,
    topUp: topUp,
    editProfileImage: editProfileImage,
    call: call,
    calender: calender,
    password: password,
    BottomHome: BottomHome,
    BottomCategory: BottomCategory,
    BottomSearch: BottomSearch,
    BottomCart: BottomCart,
    LinkedIn: linkedIn,
    Facebook: facebook,
    twitter: twitter,
    chat: chat,
    orderId: orderId,
    sideArrow: sideArrow,
    unSelected: unSelected,
    Selected: Selected,
    cart: cart,
    selectedTab: selectedTab,
    Mywishlist: Mywishlist,
    Delete: Delete,
    dropDown: dropDown,
    truck: truck,
    map: map,
    mapPin: mapPin,
    currentLocation: currentLocation,
    work: work,
    OrderDetails: OrderDetails,
    into: into,
    select: select,
    share: share,
    LightStar: LightStar,
    star: star,
    deliveryTruck: deliveryTruck,
    payment: payment,
    refund: refund,
    drawerArrow: drawerArrow,
    dark: dark,
    rtl: rtl,
    darkIcon: darkIcon,
    signOut: signOut,
    hindi:hindi,
    arabic:arabic,
    korea:korea,
    koreanWon:koreanWon,
    rupees:rupees,
    euro:euro,
    dollar:dollar,
    australianDollar:australianDollar,
    CashOnDelievry:CashOnDelievry,
}