import { hidePassword, showPassword, category, fullName, atSign, location, search, voiceSearch, decrease, increase, wishlist, home, pageList, order, language, profile, notification, currencyConverter, settings, headerArrow, markRead, discount, offer, passChange, topUp, editProfileImage,call,calender,password ,BottomHome,BottomSearch,BottomCategory,BottomCart,facebook,linkedIn, twitter,orderId} from "../assets/icons";


export const Icons = {
    hidePassword: hidePassword,
    showPassword: showPassword,
    fullName: fullName,
    category: category,
    atSign: atSign,
    location: location,
    search: search,
    voiceSearch: voiceSearch,
    decrease: decrease,
    increase: increase,
    wishlist: wishlist,
    home: home,
    pageList: pageList,
    order: order,
    language: language,
    profile: profile,
    notification: notification,
    currencyConverter: currencyConverter,
    settings: settings,
    headerArrow: headerArrow,
    markRead: markRead,
    discount: discount,
    offer: offer,
    passChange: passChange,
    topUp: topUp,
    editProfileImage:editProfileImage,
    call:call,
    calender:calender,
    password:password,
    BottomHome:BottomHome,
    BottomCategory:BottomCategory,
    BottomSearch:BottomSearch,
    BottomCart:BottomCart,
    LinkedIn:linkedIn,
    Facebook:facebook,
    twitter:twitter,
    orderId:orderId,
}